server:
  port: 9001

# ==========applicationName + druid-mysql8 driver===================
spring:
  application:
    name: provider-payment-9001

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2024?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456

# ========================mybatis===================
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: co.xiaoyuboy.entities
  configuration:
    map-underscore-to-camel-case: true